baseURL: http://richterdatascience.netlify.app/
title: Richter Data Science
theme: hugo-PaperMod
languageCode: en-us
paginate: 5

####

math: true
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: "G-75ZFXG8W71"

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: post
                  weight: 5
                #- name: Search
                  #url: search/
                  #weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10

    #fr:
        #languageName: ":fr:"
        #languageAltTitle: French
        #weight: 2
        #title: PaperModL2
        #profileMode:
            #enabled: true
            #title: PaperMod
            ## imageUrl: "#"
            ## imageTitle: my image
            ## imageWidth: 120
            ## imageHeight: 120
            #subtitle: "â˜„ï¸ Fast | â˜ï¸ Fluent | ðŸŒ™ Smooth | ðŸ“± Responsive"
            #buttons:
                #- name: Blog
                  #url: posts
                #- name: Tags
                  #url: tags
        #menu:
            #main:
                #- name: Archive
                  #url: archives/
                  #weight: 5
                #- name: Tags
                  #url: tags
                  #weight: 10
                #- name: Categories
                  #url: categories
                  #weight: 10
                #- name: Series
                  #url: series
                  #weight: 10
                #- name: NullLink
                  #url: "#"
                #- name: NullLink2
                  #url: "#"
                #- name: NullLink3
                  #url: "#"

    #fa:
        #languagedirection: rtl
        #weight: 3
        #title: PaperMod RTL
        #homeInfoParams:
            #Title: "Hi there \U0001F44B"
            #Content: Welcome to RTL layout
        #menu:
            #main:
                #- name: Tags
                  #url: tags
                  #weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "A data science blog from the PNW"
    author: Scott Richter
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: Richter Data Science
        imageUrl: "https://i.natgeofe.com/k/75ac774d-e6c7-44fa-b787-d0e20742f797/giant-panda-eating.jpg"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "For the Love of All Things Data"
        Content: 
            > 
                Hi! I'm Scott Richter, a data scientist living in Portland, Oregon. After earning an MBA in quant methods, marketing, and operations from Willamette University's Atkinson School,
                I realized the potential I could unlock by pursuing a Master's degree in data science.   
                <br />
                <br />
                I began this blog to host my capstone project en route to graduation this August. While that's how this blog begins, it's definitely not how it will end. I love digging into 
                challenging problems based on data, and will use this site to host my hobby projects, whether they're rigorous, just for fun, or a little bit of both.  
                <br />
                <br />
                This blog runs on the [Hugo PaperMod theme](https://github.com/adityatelange/hugo-PaperMod) by Aditya Telange.

    socialIcons:
        - name: github
          url: "https://github.com/ScottRichter"
        - name: linkedin
          url: "https://www.linkedin.com/in/scottjrichter/"
        - name: RsS
          url: "index.xml"

    editPost:
       URL: "https://github.com/ScottRichter/RichterDataScienceBlog/tree/main/content"
       Text: "Suggest Changes" # edit text
       appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    analytics:
       google:
           SiteVerificationTag: "G-75ZFXG8W71"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true